#!/usr/bin/env bash
# Set up web-01 server

sudo apt-get update
sudo apt-get install -y nginx

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

		location / {
		return 200 "Hello, World!\n";
	}

	# Additional server configuration...
}
EOL
sudo nginx -s reload
sudo service nginx start
