#!/usr/bin/env bash
# Set up web-01 server

sudo apt-get update
sudo apt-get install -y nginx

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

		location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

}
EOL
sudo nginx -s reload
sudo service nginx start
