#!/usr/bin/env bash
# Sets up a server with nginx and response headers

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx 
