#!/usr/bin/env bash
# Sets up a server with nginx and response headers

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i "/add_header/d; /server_name _;/a\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo nginx -s reload
sudo service nginx start
