#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  mars_frontend
        bind *:80
        mode http
        default_backend mars_frontend
backend mars_backend
        balance roundrobin
        server 390839-web-01 54.209.112.112 check
        server 390839-web-02 52.87.154.222:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart