#!/usr/bin/env bash
#This script creates  backup of all databases on root mysql user
if [ $# -ne 1 ]
then
	echo "Usage: ./5-mysql_backup PASSWORD"
else
	file_name="backup.sql"
	mysqldump -uroot -p"$1" --all-databases > "$file_name"
	timestamp=$(date +"%d-%m-%Y")
	tar -czf "$timestamp.tar.gz" "$file_name"
fi
