#!/usr/bin/env bash
# This script pings an IP address passed as an argument

if [ "$#" -gt 1 ] && [ $# -lt 1 ] && [ -n "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 8.8.8.8
fi